version: '3.8'

services:
  # 1. Postgres - источник онлайн школы
  source-postgres:
    image: postgres:15
    container_name: school-source-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: online_school
      POSTGRES_USER: school_user
      POSTGRES_PASSWORD: school_password
    ports:
      - "5432:5432"
    volumes:
      - source_postgres_data:/var/lib/postgresql/data
    networks:
      - data-warehouse-network

  # 2. S3 - staging
  minio:
    image: minio/minio
    container_name: staging-s3
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - data-warehouse-network
    
  # 3. Clickhouse
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse-dwh
    restart: unless-stopped
    ports:
      - "8123:8123"  # HTTP interface
      - "9002:9000"  # Native protocol
    environment:
      - CLICKHOUSE_DB=school_dwh
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=clickhouse_password
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - data-warehouse-network

volumes:
  source_postgres_data:
  clickhouse_data:
  minio_data:

networks:
  data-warehouse-network:
    driver: bridge
